// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_matrix
NumericVector rcpp_matrix();
RcppExport SEXP _thirdtry_rcpp_matrix() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_matrix());
    return rcpp_result_gen;
END_RCPP
}
// add_two
arma::vec add_two(arma::vec x);
RcppExport SEXP _thirdtry_add_two(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(add_two(x));
    return rcpp_result_gen;
END_RCPP
}
// read_data
arma::mat read_data(arma::mat x);
RcppExport SEXP _thirdtry_read_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(read_data(x));
    return rcpp_result_gen;
END_RCPP
}
// my_kmeans_cpp
arma::mat my_kmeans_cpp(arma::mat data, int clusters);
RcppExport SEXP _thirdtry_my_kmeans_cpp(SEXP dataSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(my_kmeans_cpp(data, clusters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thirdtry_rcpp_matrix", (DL_FUNC) &_thirdtry_rcpp_matrix, 0},
    {"_thirdtry_add_two", (DL_FUNC) &_thirdtry_add_two, 1},
    {"_thirdtry_read_data", (DL_FUNC) &_thirdtry_read_data, 1},
    {"_thirdtry_my_kmeans_cpp", (DL_FUNC) &_thirdtry_my_kmeans_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_thirdtry(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
