# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_matrix <- function() {
    .Call(`_thirdtry_rcpp_matrix`)
}

add_two <- function(x) {
    .Call(`_thirdtry_add_two`, x)
}

read_data <- function(x) {
    .Call(`_thirdtry_read_data`, x)
}

